name = "email-workers"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "8d8fff2b8b2d4f0328c8f0b438de5425"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "b6f17666758845cb94ba198f53dfa376"
